name: Cypress Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
    - uses: actions/checkout@v3.5.2
    
    - name: Install dependences
      run: yarn install
      
    - name: Run E2E tests
      run: yarn cypres run
    
